version: "3.9"

services:
  fastapi-service:
    build: .
    container_name: bot-ai-agent-itmo
    ports:
      - "5000:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
